PROJECT=makeshift
PROJECTSOURCE=$(PROJECT).asm
PROJECTTARGET=$(PROJECT).prg
PROJECTSYM=$(PROJECT).sym

PACKEDINTRO=packed-intro.bin
PACKREPORT=report.html

INTRO=intro
INTROSOURCE=$(INTRO).asm
INTROTARGET=$(INTRO).bin
INTROSYM=$(INTRO).sym

MUSIC=music
MUSICSOURCE=$(MUSIC).asm
MUSICTARGET=$(MUSIC).prg
MUSICSYM=$(MUSIC).sym

FLDTEXT=fld-text
FLDTEXTDIR=$(FLDTEXT)
FLDTEXTSOURCE=$(FLDTEXTDIR)/$(FLDTEXT).asm
FLDTEXTINC=$(FLDTEXTDIR)/$(FLDTEXT).inc
FLDTEXTCODETARGET=$(FLDTEXTDIR)/$(FLDTEXT).prg
FLDTEXTDATATARGET=$(FLDTEXTDIR)/$(FLDTEXT)-data.prg
FLDTEXTSYM=$(FLDTEXTDIR)/$(FLDTEXT).sym

ZOOMPLASMA=zoom-plasma
ZOOMPLASMADIR=$(ZOOMPLASMA)
ZOOMPLASMASOURCE=$(ZOOMPLASMADIR)/$(ZOOMPLASMA).asm
ZOOMPLASMAINC=$(ZOOMPLASMADIR)/$(ZOOMPLASMA).inc
ZOOMPLASMACODETARGET=$(ZOOMPLASMADIR)/$(ZOOMPLASMA).prg
ZOOMPLASMADATATARGET=$(ZOOMPLASMADIR)/$(ZOOMPLASMA)-data.prg
ZOOMPLASMASYM=$(ZOOMPLASMADIR)/$(ZOOMPLASMA).sym

LAYERS=layers
LAYERSDIR=$(LAYERS)
LAYERSSOURCE=$(LAYERSDIR)/$(LAYERS).asm
LAYERSINC=$(LAYERSDIR)/$(LAYERS).inc
LAYERSCODETARGET=$(LAYERSDIR)/$(LAYERS).prg
LAYERSDATATARGET=$(LAYERSDIR)/$(LAYERS)-data.prg
LAYERSSYM=$(LAYERSDIR)/$(LAYERS).sym

SINEBOXES=sine-boxes
SINEBOXESDIR=$(SINEBOXES)
SINEBOXESSOURCE=$(SINEBOXESDIR)/$(SINEBOXES).asm
SINEBOXESINC=$(SINEBOXESDIR)/$(SINEBOXES).inc
SINEBOXESCODETARGET=$(SINEBOXESDIR)/$(SINEBOXES).prg
SINEBOXESDATATARGET=$(SINEBOXESDIR)/$(SINEBOXES)-data.prg
SINEBOXESSYM=$(SINEBOXESDIR)/$(SINEBOXES).sym

COMMONINC=common.inc
BASICINC=basic.inc

DISK=$(PROJECT).d64

EMU=x64
EMUSC=x64sc
EMUFLAGS=

RM=rm
RMFLAGS=-f

PACKER=admiral-p4kbar
PACKERDIR=$(PACKER)
PACKERFLAGS=--release
PACKERSPEED=instant

all: $(PROJECTTARGET)

$(PROJECTTARGET): $(PROJECTSOURCE) $(COMMONINC) $(BASICINC) $(INTROTARGET) $(PACKEDINTRO)
	kickass -showmem $(PROJECTSOURCE)

$(PACKEDINTRO) $(PACKREPORT): packer $(INTROTARGET)
	cd $(PACKERDIR) && cargo run $(PACKERFLAGS) -- $(CURDIR)/$(INTROTARGET) $(CURDIR)/$(PACKEDINTRO) $(CURDIR)/$(PACKREPORT) $(PACKERSPEED)

packer:
	cd $(PACKERDIR) && cargo build --release

$(INTROTARGET) $(INTROSYM): $(INTROSOURCE) $(MUSICTARGET) $(FLDTEXTCODETARGET) $(FLDTEXTDATATARGET) $(FLDTEXTINC) $(ZOOMPLASMACODETARGET) $(ZOOMPLASMADATATARGET) $(ZOOMPLASMAINC) $(LAYERSCODETARGET) $(LAYERSDATATARGET) $(LAYERSINC) $(SINEBOXESCODETARGET) $(SINEBOXESDATATARGET) $(SINEBOXESINC) $(COMMONINC) $(BASICINC)
	kickass -showmem -binfile $(INTROSOURCE)

$(MUSICTARGET) $(MUSICSYM): $(MUSICSOURCE)
	kickass -showmem $(MUSICSOURCE)

$(FLDTEXTCODETARGET) $(FLDTEXTDATATARGET) $(FLDTEXTSYM): $(FLDTEXTSOURCE) $(FLDTEXTINC) $(COMMONINC) $(BASICINC) $(ZOOMPLASMAINC)
	kickass -showmem $(FLDTEXTSOURCE)

$(ZOOMPLASMACODETARGET) $(ZOOMPLASMADATATARGET) $(ZOOMPLASMASYM): $(ZOOMPLASMASOURCE) $(ZOOMPLASMAINC) $(COMMONINC) $(BASICINC) $(SINEBOXESINC)
	kickass -showmem $(ZOOMPLASMASOURCE)

$(LAYERSCODETARGET) $(LAYERSDATATARGET) $(LAYERSSYM): $(LAYERSSOURCE) $(LAYERSINC) $(COMMONINC) $(BASICINC) $(FLDTEXTINC)
	kickass -showmem $(LAYERSSOURCE)

$(SINEBOXESCODETARGET) $(SINEBOXESDATATARGET) $(SINEBOXESSYM): $(SINEBOXESSOURCE) $(SINEBOXESINC) $(COMMONINC) $(BASICINC) $(LAYERSINC)
	kickass -showmem $(SINEBOXESSOURCE)

pack: $(PACKEDINTRO)

# Instead of actually creating the disk, we get cheeky here and just replace the intro/note files
#  in a pre-made disk file. This gets around certain 1541 limitations like no duplicate filenames 
#  and still allows us to just use the disk tool that comes with VICE.
$(DISK): $(PROJECTTARGET)
	c1541 -attach $(DISK) -write $(PROJECTTARGET) "@0:   makeshift    "

disk: $(DISK)

test: $(DISK)
	$(EMU) $(EMUFLAGS) $(DISK)

testsc: $(DISK)
	$(EMUSC) $(EMUFLAGS) $(DISK)

clean:
	$(RM) $(RMFLAGS) $(PROJECTTARGET) $(PROJECTSYM)
	$(RM) $(RMFLAGS) $(PACKEDINTRO) $(PACKREPORT)
	$(RM) $(RMFLAGS) $(INTROTARGET) $(INTROSYM)
	$(RM) $(RMFLAGS) $(MUSICTARGET) $(MUSICSYM)
	$(RM) $(RMFLAGS) $(FLDTEXTCODETARGET) $(FLDTEXTDATATARGET) $(FLDTEXTSYM)
	$(RM) $(RMFLAGS) $(ZOOMPLASMACODETARGET) $(ZOOMPLASMADATATARGET) $(ZOOMPLASMASYM)
	$(RM) $(RMFLAGS) $(LAYERSCODETARGET) $(LAYERSDATATARGET) $(LAYERSSYM)
	$(RM) $(RMFLAGS) $(SINEBOXESCODETARGET) $(SINEBOXESDATATARGET) $(SINEBOXESSYM)
	cd $(PACKERDIR) && cargo clean
